### ISSUE TITLE
preprocessed feature vector 

### ISSUE THREAD

**Issue by titizheng** [hustvl/MMIL-Transformer#4]
Regarding the “preprocessed feature vector” you provided, were the coordinate points extracted at level 1? Additionally, could you please specify the segmentation parameters used when preprocessing the data using the create_patch.py from CLAM? I've noticed a significant disparity in the number of data points and the range of coordinate values extracted from the 16th Breast Cancer Challenge test dataset when I utilized the default CLAM parameters for data preprocessing, compared to the values you've mentioned. 
This difference resulted in a decrease of 0.07 in accuracy when I tested with the pretrained parameters you provided. Could you kindly explain this situation to me?"

**Comment by K1seki221** [comment]
Thanks for your attention! We preprocess WSIs in CAMELYON16 at level 1 and with 256x256 resolution, which can be specified by 'python create_patches_fp.py --patch_size 256 --patch_level 1'. You are supposed to get:
[train: normal: 1661186, tumor:1341944] [test: 1607557], total 4610687 coordinates. （normal001.h5 has 2085 coordinates）

segmentation parameters you might set as:
'''
 seg_params = {'seg_level': -1, 'sthresh': 8, 'mthresh': 7, 'close': 4, 'use_otsu': False, 'keep_ids': 'none', 'exclude_ids': 'none'},
filter_params = {'a_t':100, 'a_h': 16, 'max_n_holes':8}
'''
