### ISSUE TITLE
TCGA-LUNG数据预处理过程的相关问题

### ISSUE THREAD

**Issue by zmcwsd** [hustvl/MMIL-Transformer#5]
非常感谢你们的工作，我想请教一下，1.TCGA-LUNG数据预处理过程，提取的patch size是多大，在那个倍率下提取的。
2.提供的LUNG的feature vector 是基于ResNet18的还是ResNet50，3.特征提取器是否经过自监督对比训练。

**Comment by K1seki221** [comment]
Thanks@zmcwsd for your attention. Please refer to the configuration of data preprocessing in [DSMIL](https://github.com/binli123/dsmil-wsi), we simply implemented the same setting.

**Comment by zmcwsd** [comment]
Thanks，但是我还是有些疑问，再次感谢你们的工作，DSMIL使用的是ResNet18，并且使用自监督训练的方式，作为特征提取器，
![11f05f517d6e0229de0edada08f3e82](https://github.com/hustvl/MMIL-Transformer/assets/93756127/9cfb2e40-e3b2-4cac-a94f-022923a2d328)
但是你们的论文里面的结果写的是ResNet50，并且在数据处理部分说使用的DSMIL，这有一点矛盾
![2ba38538a67f09c054986de4dae49a3](https://github.com/hustvl/MMIL-Transformer/assets/93756127/58474af0-31f7-4037-bb2a-f971e3f70b43)
![6ab1869a20b77a774505f60fad5124a](https://github.com/hustvl/MMIL-Transformer/assets/93756127/cc99a8ba-9404-4d69-9124-42a5d98f9aa8)

感谢您的解答！

**Comment by K1seki221** [comment]
Thanks @zmcwsd for your dedication. It seems we didn't correctly title [Table 1] in our paper. Table 1 reports the results of ResNet-50 on Camelyon16, and ResNet-18 as the same as DSMIL on TCGA-NSCLC. We will soon revise it. Thanks again!
